# Generated by Django 5.1.1 on 2024-10-03 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpartner',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='activity',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assigned',
            name='role_name',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='actual_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_name',
            field=models.ForeignKey(default='DEFAULT', on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.CreateModel(
            name='OnProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('is_client', models.BooleanField()),
                ('is_partner', models.BooleanField()),
                ('description', models.TextField()),
                ('client_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clientpartner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project')),
            ],
            options={
                'db_table': 'on_project',
            },
        ),
    ]
