# Generated by Django 4.2.16 on 2024-09-28 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_employee_react_firstname_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "username",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=45)),
                ("first_name", models.CharField(max_length=45)),
                ("last_name", models.CharField(max_length=45)),
                ("email", models.CharField(max_length=45)),
                ("project_manager", models.BooleanField(default=False)),
            ],
        ),
    ]
