# Generated by Django 4.2.16 on 2024-10-08 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_clientpartner_phone_no_activity_budget_and_more"),
        ("app", "0003_useraccount"),
    ]

    operations = []
