# Generated by Django 4.2.16 on 2024-10-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_project_project_manager_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="spent_budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
