# Generated by Django 4.2.16 on 2024-10-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_project_spent_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                default=False,
                limit_choices_to={"project_manager": True},
                on_delete=django.db.models.deletion.CASCADE,
                to="app.useraccount",
            ),
        ),
    ]
