# Generated by Django 4.2.16 on 2024-10-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_project_project_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"project_manager": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.useraccount",
            ),
        ),
    ]
