# Generated by Django 4.2.16 on 2024-10-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_project_project_manager"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmanager",
            name="user_account",
            field=models.CharField(default="DEFAULT", max_length=20),
        ),
    ]
